name: eodb
description: "Essential oil database."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  diacritic: ^0.1.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/eoscraper/
    - assets/eoscraper/compounds/
    - assets/eoscraper/oils/