name: eodb
description: 'Essential oil database.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cupertino_icons: ^1.0.9
  diacritic: ^0.1.6
  fl_chart: ^1.2.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.1.0
  very_good_analysis: ^10.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/eoscraper/
    - assets/eoscraper/compounds/
    - assets/eoscraper/oils/

icons_launcher:
  image_path: 'assets/icon.png'
  platforms:
    android:
      enable: true
    ios:
      enable: true
    macos:
      enable: true
    windows:
      enable: true
    web:
      enable: true
    linux:
      enable: true